backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "about"
    label: "About"
    folder: "about"
    files:    
      - file: "site/content/about.en.md"
        label: "About (en)"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Type, name: type, widget: hidden, default: about}
          - {label: Page, name: page, widget: hidden, default: './about.html'}
          - {label: Us, name: us, widget: object, fields:[
              {label: Heading, name: heading, widget: string},
              {label: Description, name: description, widget: text}
          ]}
  - name: "index"
    label: "Index"
    files:
      - file: "site/content/_index.en.md"
        label: "Home page (en)"
        name: "Index-en"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Type, name: type, widget: hidden, default: _index}
          - {label: Heading, name: head, widget: object, fields:[
              {label: Title, name: title, widget: string}
          ]}
          - {label: intro, name: intro, widget: object, fields:[
              {label: Why, name: why, widget: string},
              {label: Reason, name: reason, widget: string}
          ]}
          - {label: Middle, name: middle, widget: object, fields:[
              {label: Head, name: head, widget: string},
              {label: Content, name: content, widget: text},
              {label: Image, name: image, widget: image},
              {label: Link, name: link, widget: string}
          ]}
          - {label: Offers, name: offers, widget: object, fields:[
              {label: Head, name: head, widget: string},
              {label: First, name: first, widget: text},
              {label: Second, name: second, widget: text},
              {label: Third, name: third, widget: text},              
              {label: Link, name: link, widget: string}
          ]}    
