baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
#sectionPagesMenu = "main"

[params]
    custom_css = ["css/dropdown.css"]
    custom_js = ["js/dropdown.js"]

[languages.en]
title = "Homepage"

[[languages.en.menu.main]]
title = "News"
url    = "/en/post/"
name   = "News"
weight = 4

[languages.fr]
title = "Accueil"

[[languages.fr.menu.main]]
title = "Actualites"
url    = "/fr/post/"
name   = "Actualités"
weight = 4

[languages.es]
title = "Inicio"

[[languages.es.menu.main]]
title = "Noticias"
url    = "/es/post/"
name   = "Noticias"
weight = 4
