baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
#sectionPagesMenu = "main"

[languages.en]
title = "Homepage"

[[languages.en.menu.main]]
url    = "/en/post"
name   = "News"
weight = 4

[languages.fr]
title = "Accueil"

[[languages.fr.menu.main]]
url    = "/fr/post"
name   = "Actualites"
weight = 4
